apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: horizon
  namespace: openstack
spec:
  chart:
    spec:
      chart: horizon
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openstack-helm
  interval: 1m0s
  dependsOn:
    - name: mariadb
    - name: memcached
    - name: rabbitmq
    - name: keystone
  valuesFrom:
    - kind: ConfigMap
      name: openstack-endpoints
      valuesKey: values.yaml
    - kind: Secret
      name: openstack-secrets
      valuesKey: oslo-db
    - kind: Secret
      name: openstack-secrets
      valuesKey: oslo-messaging
    - kind: Secret
      name: openstack-secrets
      valuesKey: oslo-cache
    - kind: Secret
      name: openstack-secrets
      valuesKey: horizon-identity
    # - kind: ConfigMap
    #   name: openstack-endpoints
    #   valuesKey: horizon-values
  values:
    images:
      tags:
        db_init: quay.io/airshipit/heat:2025.1-ubuntu_noble
        db_drop: quay.io/airshipit/heat:2025.1-ubuntu_noble
        horizon_db_sync: quay.io/airshipit/horizon:2025.1-ubuntu_noble
        horizon: quay.io/airshipit/horizon:2025.1-ubuntu_noble
    conf:
      horizon:
        local_settings:
          config:
            openstack_enable_password_retrieve: "True"
            secure_proxy_ssl_header: true
            csrf_trusted_origins:
              - "https://openstack.moonpiedumpl.ing"
            auth:
              sso:
                enabled: True
                websso_keystone_url: "https://keystone.openstack.moonpiedumpl.ing/v3"
              sso_inital_choice: credentials
              idp_mapping:
                - name: "authentik"
                  label: "Sign in with authentik"
                  idp: "sso"
                  protocol: "openid"
            allowed_hosts:
              - openstack.moonpiedumpl.ing
    network:
      dashboard:
        ingress:
          public: true
          classes:
            namespace: "nginx"
            cluster: "nginx-cluster"
          annotations:
            nginx.ingress.kubernetes.io/rewrite-target: /
            cert-manager.io/cluster-issuer: letsencrypt-prod  
            nginx.ingress.kubernetes.io/proxy-body-size: 25G
