---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keystone
  namespace: openstack
spec:
  chart:
    spec:
      chart: keystone
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openstack-helm
  interval: 1m0s
  install:
    disableWait: true
  dependsOn:
    - name: mariadb
    - name: memcached
    - name: rabbitmq
  valuesFrom:
    - kind: ConfigMap
      name: openstack-endpoints
      valuesKey: values.yaml
  values:
    images:
      tags:
        bootstrap: "quay.io/airshipit/heat:2025.1-ubuntu_noble"
        db_init: "quay.io/airshipit/heat:2025.1-ubuntu_noble"
        db_drop: "quay.io/airshipit/heat:2025.1-ubuntu_noble"
        keystone_api: "quay.io/airshipit/keystone:2025.1-ubuntu_noble"
        keystone_bootstrap: "quay.io/airshipit/heat:2025.1-ubuntu_noble"
        keystone_credential_rotate: "quay.io/airshipit/keystone:2025.1-ubuntu_noble"
        keystone_credential_setup: "quay.io/airshipit/keystone:2025.1-ubuntu_noble"
        keystone_db_sync: "quay.io/airshipit/keystone:2025.1-ubuntu_noble"
        keystone_domain_manage: "quay.io/airshipit/keystone:2025.1-ubuntu_noble"
        keystone_fernet_rotate: "quay.io/airshipit/keystone:2025.1-ubuntu_noble"
        keystone_fernet_setup: "quay.io/airshipit/keystone:2025.1-ubuntu_noble"
        ks_user: "quay.io/airshipit/heat:2025.1-ubuntu_noble"