---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: neutron
  namespace: openstack
spec:
  chart:
    spec:
      chart: neutron
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openstack-helm
  interval: 1m0s
  install:
    disableWait: true
  timeout: 30m0s
  dependsOn:
    - name: mariadb
    - name: memcached
    - name: rabbitmq
    - name: keystone
  valuesFrom:
    - kind: ConfigMap
      name: openstack-endpoints
      valuesKey: values.yaml
    - kind: Secret
      name: openstack-secrets
      valuesKey: oslo-db
    - kind: Secret
      name: openstack-secrets
      valuesKey: oslo-messaging
    - kind: Secret
      name: openstack-secrets
      valuesKey: oslo-cache
    - kind: Secret
      name: openstack-secrets
      valuesKey: neutron-identity
  values:
    images:
      tags:
        bootstrap: "quay.io/airshipit/heat:2025.1-ubuntu_noble"
        db_init: "quay.io/airshipit/heat:2025.1-ubuntu_noble"
        db_drop: "quay.io/airshipit/heat:2025.1-ubuntu_noble"
        ks_user: "quay.io/airshipit/heat:2025.1-ubuntu_noble"
        ks_service: "quay.io/airshipit/heat:2025.1-ubuntu_noble"
        ks_endpoints: "quay.io/airshipit/heat:2025.1-ubuntu_noble"
        neutron_db_sync: "quay.io/airshipit/neutron:2025.1-ubuntu_noble"
        neutron_dhcp: "quay.io/airshipit/neutron:2025.1-ubuntu_noble"
        neutron_l3: "quay.io/airshipit/neutron:2025.1-ubuntu_noble"
        neutron_l2gw: "quay.io/airshipit/neutron:2025.1-ubuntu_noble"
        neutron_linuxbridge_agent: "quay.io/airshipit/neutron:2025.1-ubuntu_noble"
        neutron_metadata: "quay.io/airshipit/neutron:2025.1-ubuntu_noble"
        neutron_ovn_metadata: "quay.io/airshipit/neutron:2025.1-ubuntu_noble"
        neutron_openvswitch_agent: "quay.io/airshipit/neutron:2025.1-ubuntu_noble"
        neutron_server: "quay.io/airshipit/neutron:2025.1-ubuntu_noble"
        neutron_rpc_server: "quay.io/airshipit/neutron:2025.1-ubuntu_noble"
        neutron_bagpipe_bgp: "quay.io/airshipit/neutron:2025.1-ubuntu_noble"
        neutron_netns_cleanup_cron: "quay.io/airshipit/neutron:2025.1-ubuntu_noble"
    conf:
      neutron:
        DEFAULT:
          l3_ha: False
          max_l3_agents_per_router: 1
      # <provider_interface_name> will be attached to the br-ex bridge.
      # The IP assigned to the interface will be moved to the bridge.
      auto_bridge_add:
        br-ex: eth2
      plugins:
        ml2_conf:
          ml2_type_flat:
            flat_networks: public
        openvswitch_agent:
          ovs:
            bridge_mappings: public:br-ex