---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openfga
  namespace: openfga
spec:
  chart:
    spec:
      chart: openfga
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openfga
  interval: 1m0s
  valuesFrom:
    - kind: Secret
      name: openfga-secrets
      valuesKey: values.yaml
  values:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        acme.cert-manager.io/http01-edit-in-place: "true"
      hosts:
        - host: openfga.moonpiedumpl.ing
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: openfga-tls
          hosts: 
            - openfga.moonpiedumpl.ing
    replicaCount: 1
    datastore:
      engine: postgres
    postgresql: 
      enabled: true
      auth:
        database: postgres
    authn:
      method: preshared
    playground:
      enabled: false

