---
apiVersion: v1
kind: Service
metadata:
  name: pangolin
  namespace: pangolin
spec:
  selector:
    app: pangolin
  ports:
    - name: http
      port: 3001
      targetPort: http
      protocol: TCP
  type: ClusterIP
---
# Internal cluster IP so other pods can reach gerbil by name, and
# also a LoadBalancer for TCP (80/443). Many environments prefer splitting TCP/UDP.
apiVersion: v1
kind: Service
metadata:
  name: gerbil
  namespace: pangolin
spec:
  selector:
    app: gerbil
  ports:
    - name: grpc
      port: 3004
      targetPort: grpc
      protocol: TCP
  type: ClusterIP
#---
# apiVersion: v1
# kind: Service
# metadata:
#   name: gerbil-tcp
#   namespace: pangolin
# spec:
#   selector:
#     app: gerbil
#   type: LoadBalancer
#   ports:
#     - name: http
#       port: 80
#       targetPort: web-80
#       protocol: TCP
#     - name: https
#       port: 443
#       targetPort: web-443
#       protocol: TCP