---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blog
  namespace: blog
spec:
  chart:
    spec:
      chart: nginx
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nginx
      version: "18.2.4"
  interval: 1m0s
  values:
    cloneStaticSiteFromGit:
      enabled: true
      repository: https://github.com/moonpiedumplings/moonpiedumplings.github.io
      branch: gh-pages
      # 60 seconds is the default
      interval: 60
    # ingress:
    #   enabled: true
    #   hostname: moonpiedumpl.ing
    #   annotations:
    #     cert-manager.io/issuer: "letsencrypt-staging"
    #     acme.cert-manager.io/http01-edit-in-place: "true"
    #   tls:
    #     secret: 
