---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: openfga-postgres
  namespace: openfga
spec:
  instances: 1
  # See rolling updates
  # https://cloudnative-pg.io/documentation/1.27/postgres_upgrades/
  imageName: ghcr.io/cloudnative-pg/postgresql:17.6
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi
      storageClassName: longhorn-databases
      volumeMode: Filesystem
  backup:
    volumeSnapshot:
       className: longhorn-snapshot
  bootstrap:
    initdb:
      database: openfga
      owner: openfga
      secret:
        name: openfga-db-secret
  managed:
    services:
      disabledDefaultServices: ["ro", "r"]
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: daily-openfga
  namespace: openfga
  annotations:
    backup.cnpg.io/volumeSnapshotDeadline: "20"
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: openfga-postgres
  method: volumeSnapshot