---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openfga
  namespace: openfga
spec:
  chart:
    spec:
      chart: openfga
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openfga
  interval: 1m0s
  install:
    disableWait: true
  valuesFrom:
    - kind: Secret
      name: openfga-secrets
      valuesKey: values.yaml
  values:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - host: openfga.moonpiedumpl.ing
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: openfga-tls
          hosts: 
            - openfga.moonpiedumpl.ing
    replicaCount: 1
    datastore:
      engine: postgres
    postgresql:
      enabled: false
      auth:
        database: postgres
        # In the secret
        # postgresPassword: secretpasswrod
    # In the secret
    # datastore:
    #   uri: "postgres://postgres:password@openfga-postgres-rw.openfga.svc.cluster.local:5432/postgres?sslmode=disable"
    authn:
      method: preshared
      # In the secret
      # preshared:
      #   keys: ["secretkey"]
    playground:
      enabled: false