---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coder
  namespace: coder
spec:
  chart:
    spec:
      chart: coder
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: coder
      version: "<=2.27"
  interval: 10m0s
  values:
    coder:
      env: 
        #  Enable for initial install, disable otherwise
        - name: CODER_DISABLE_PASSWORD_AUTH
          value: "true"
        - name: CODER_OAUTH2_GITHUB_DEFAULT_PROVIDER_ENABLE
          value: "false"
        - name: CODER_OIDC_ISSUER_URL
          value: "https://idp.moonpiedumpl.ing/application/o/coder/"
        - name: CODER_OIDC_IGNORE_EMAIL_VERIFIED
          value: "true"
        - name: CODER_OIDC_CLIENT_ID
          value: "sJ1kfuBz91QSDMqvMRZXi6ogiV8R8oImwg6lTigh"
        - name: CODER_ACCESS_URL
          value: "https://coder.moonpiedumpl.ing"
        - name: CODER_WILDCARD_ACCESS_URL
          value: "*.coder.moonpiedumpl.ing"
        - name: CODER_OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: coder-secret
              key: CODER_OIDC_CLIENT_SECRET
        - name: CODER_PG_CONNECTION_URL
          valueFrom:
            secretKeyRef:
              name: coder-secret
              key: CODER_PG_CONNECTION_URL
      service:
        enable: true
        type: ClusterIP
      ingress:
        enable: true
        host: "coder.moonpiedumpl.ing"
        wildcardHost: "*.coder.moonpiedumpl.ing"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          acme.cert-manager.io/http01-edit-in-place: "true"
        tls:
          enable: true
          secretName: "coder-ssl"
          wildcardSecretName: "coder-wildcard-ssl"
      serviceAccount:
        extraRules:
          - apiGroups: [""]
            resources: ["configmaps"]
            verbs:
              - create
              - delete
              - deletecollection
              - get
              - list
              - patch
              - update
              - watch
