apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: coder-workspaces
  namespace: coder
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: coder-workspace
  policyTypes:
  - Ingress
  - Egress
  egress:
  - {}