---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cinder
  namespace: openstack
spec:
  chart:
    spec:
      chart: cinder
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openstack
  interval: 1m0s
  timeout: 10m0s
  values:
    images:
      tags:
        db_init: "docker.io/openstackhelm/heat:2024.2-ubuntu_jammy"
        cinder_db_sync: "docker.io/openstackhelm/cinder:2024.2-ubuntu_jammy"
        db_drop: "docker.io/openstackhelm/heat:2024.2-ubuntu_jammy"
        ks_user: "docker.io/openstackhelm/heat:2024.2-ubuntu_jammy"
        ks_service: "docker.io/openstackhelm/heat:2024.2-ubuntu_jammy"
        ks_endpoints: "docker.io/openstackhelm/heat:2024.2-ubuntu_jammy"
        cinder_api: "docker.io/openstackhelm/cinder:2024.2-ubuntu_jammy"
        bootstrap: "docker.io/openstackhelm/heat:2024.2-ubuntu_jammy"
        cinder_scheduler: "docker.io/openstackhelm/cinder:2024.2-ubuntu_jammy"
        cinder_volume: "docker.io/openstackhelm/cinder:2024.2-ubuntu_jammy"
        cinder_volume_usage_audit: "docker.io/openstackhelm/cinder:2024.2-ubuntu_jammy"
        cinder_storage_init: "docker.io/openstackhelm/ceph-config-helper:latest-ubuntu_jammy"
        cinder_backup: "docker.io/openstackhelm/cinder:2024.2-ubuntu_jammy"
        cinder_backup_storage_init: "docker.io/openstackhelm/ceph-config-helper:latest-ubuntu_jammy"