---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keystone
  namespace: openstack
spec:
  chart:
    spec:
      chart: keystone
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openstack
  interval: 1m0s
  dependsOn:
    - name: mariadb
    - name: memcached
    - name: rabbitmq
  values:
    images:
      tags:
        bootstrap: "docker.io/openstackhelm/heat:2024.2-ubuntu_jammy"
        db_init: "docker.io/openstackhelm/heat:2024.2-ubuntu_jammy"
        db_drop: "docker.io/openstackhelm/heat:2024.2-ubuntu_jammy"
        keystone_api: "docker.io/openstackhelm/keystone:2024.2-ubuntu_jammy"
        keystone_bootstrap: "docker.io/openstackhelm/heat:2024.2-ubuntu_jammy"
        keystone_credential_rotate: "docker.io/openstackhelm/keystone:2024.2-ubuntu_jammy"
        keystone_credential_setup: "docker.io/openstackhelm/keystone:2024.2-ubuntu_jammy"
        keystone_db_sync: "docker.io/openstackhelm/keystone:2024.2-ubuntu_jammy"
        keystone_domain_manage: "docker.io/openstackhelm/keystone:2024.2-ubuntu_jammy"
        keystone_fernet_rotate: "docker.io/openstackhelm/keystone:2024.2-ubuntu_jammy"
        keystone_fernet_setup: "docker.io/openstackhelm/keystone:2024.2-ubuntu_jammy"
        ks_user: "docker.io/openstackhelm/heat:2024.2-ubuntu_jammy"