---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nova
  namespace: openstack
spec:
  chart:
    spec:
      chart: nova
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openstack
  interval: 1m0s
  values:
    images:
      tags:
        bootstrap: "docker.io/openstackhelm/heat:2024.2-ubuntu_jammy"
        db_drop: "docker.io/openstackhelm/heat:2024.2-ubuntu_jammy"
        db_init: "docker.io/openstackhelm/heat:2024.2-ubuntu_jammy"
        ks_user: "docker.io/openstackhelm/heat:2024.2-ubuntu_jammy"
        ks_service: "docker.io/openstackhelm/heat:2024.2-ubuntu_jammy"
        ks_endpoints: "docker.io/openstackhelm/heat:2024.2-ubuntu_jammy"
        nova_api: "docker.io/openstackhelm/nova:2024.2-ubuntu_jammy"
        nova_cell_setup: "docker.io/openstackhelm/nova:2024.2-ubuntu_jammy"
        nova_cell_setup_init: "docker.io/openstackhelm/heat:2024.2-ubuntu_jammy"
        nova_compute: "docker.io/openstackhelm/nova:2024.2-ubuntu_jammy"
        nova_compute_ssh: "docker.io/openstackhelm/nova:2024.2-ubuntu_jammy"
        nova_conductor: "docker.io/openstackhelm/nova:2024.2-ubuntu_jammy"
        nova_db_sync: "docker.io/openstackhelm/nova:2024.2-ubuntu_jammy"
        nova_novncproxy: "docker.io/openstackhelm/nova:2024.2-ubuntu_jammy"
        nova_novncproxy_assets: "docker.io/openstackhelm/nova:2024.2-ubuntu_jammy"
        nova_scheduler: "docker.io/openstackhelm/nova:2024.2-ubuntu_jammy"
        nova_spiceproxy: "docker.io/openstackhelm/nova:2024.2-ubuntu_jammy"
        nova_spiceproxy_assets: "docker.io/openstackhelm/nova:2024.2-ubuntu_jammy"
        nova_service_cleaner: "docker.io/openstackhelm/ceph-config-helper:latest-ubuntu_jammy"
    conf:
      ceph:
        enabled: true
    bootstrap:
      wait_for_computes:
        enabled: true