---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: placement
  namespace: openstack
spec:
  chart:
    spec:
      chart: placement
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openstack
  interval: 1m0s
  dependsOn:
    - name: mariadb
    - name: memcached
    - name: rabbitmq
    - name: keystone
    - name: nova
  values:
    images:
      pull_policy: IfNotPresent
      tags:
        placement: "docker.io/openstackhelm/placement:2024.2-ubuntu_jammy"
        ks_user: "docker.io/openstackhelm/heat:2024.2-ubuntu_jammy"
        ks_service: "docker.io/openstackhelm/heat:2024.2-ubuntu_jammy"
        ks_endpoints: "docker.io/openstackhelm/heat:2024.2-ubuntu_jammy"
        db_init: "docker.io/openstackhelm/heat:2024.2-ubuntu_jammy"
        db_drop: "docker.io/openstackhelm/heat:2024.2-ubuntu_jammy"
        placement_db_sync: "docker.io/openstackhelm/placement:2024.2-ubuntu_jammy"
        dep_check: "quay.io/airshipit/kubernetes-entrypoint:latest-ubuntu_focal"
        image_repo_sync: "docker.io/docker:17.07.0"
    dependencies:
      static:
        db_sync:
          jobs:
            - placement-db-init