---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  chart:
    spec:
      chart: authentik
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: authentik
        # Figure out what version I should have
      # version: 
  interval: 1m0s
  valuesFrom:
    - kind: Secret
      name: authentik-secrets
      valuesKey: values.yaml
  values:
    authentik:
        # secret_key: "PleaseGenerateASecureKey"
        # This sends anonymous usage-data, stack traces on errors and
        # performance data to sentry.io, and is fully opt-in
        error_reporting:
            enabled: true
        # postgresql:
        #     password: "ThisIsNotASecurePassword"
    server:
        ingress:
            # Should default to nginx already
            # ingressClassName: nginx
            # Change to true when done
            enabled: true
            hosts:
                - sso.moonpiedumpl.ing
            annotations:
                cert-manager.io/cluster-issuer: "letsencrypt-prod"
                acme.cert-manager.io/http01-edit-in-place: "true"
            tls:
              - hosts: [sso.moonpiedumpl.ing]
                secretName: sso-acme
        env:
          # Otherwise, authentik doesn't see the real ip address of connections from the proxy
          - name: AUTHENTIK_LISTEN__TRUSTED_PROXY_CIDRS
            value: "127.0.0.0/8, 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, fe80::/10, ::1/128, 130.166.79.34/32"


    postgresql:
        enabled: true
        # auth:
        #     password: "ThisIsNotASecurePassword"
    redis:
        enabled: true
    