apiVersion: v1
kind: Secret
metadata:
  name: authentik-secrets
  namespace: default
type: Opaque
stringData:
  values.yaml: |
    authentik:
      secret_key: "PleaseGenerateASecureKey"
      postgresql:
        password: "ThisIsNotASecurePassword"
    postgresql:
      auth:
        password: "ThisIsNotASecurePassword"