---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      version: v1.16.0
  interval: 1m0s
  values:
    crds:
      enabled: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: porkbun-webhook
  namespace: cert-manager
spec:
  releaseName: porkbun-webhook
  chart:
    spec:
      chart: cert-manager-porkbun-webhook
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: porkbun-webhook
      version: 1.0.3
  interval: 1m0s
  values:
    groupName: moonpiedumpl.ing
