---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 1m0s
  url: https://charts.jetstack.io
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: porkbun-webhook
  namespace: cert-manager
spec:
  type: oci
  interval: 5m0s
  url: oci://ghcr.io/lost-woods/charts/cert-manager-porkbun-webhook

