---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      version: "<=1.18"
  interval: 1m0s
  values:
    crds:
      enabled: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: porkbun-webhook
  namespace: cert-manager
spec:
  releaseName: porkbun-webhook
  chart:
    spec:
      chart: ./deploy/porkbun-webhook
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: porkbun-webhook
        namespace: cert-manager
  interval: 1m0s
  values:
    groupName: moonpiedumpl.ing

    
