---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: porkbun-secret:reader
  namespace: cert-manager
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["porkbun-secret"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: porkbun-webhook:secret-reader
  namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: porkbun-secret:reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: porkbun-webhook