---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      # version: 
  postRenderers:
    - kustomize:
        patches:
          - patch: |
              - op:  add
                path: /spec/template/spec/containers/0/ports/-
                value:
                  containerPort: 22
                  hostPort: 22
                  name: ssh
                  protocol: TCP
            target:
              kind: Deployment
              name: ingress-nginx-controller
  interval: 1m0s
  values:
    controller:
      updateStategy:
        type: rollingUpdate
        rollingUpdate:
          maxSurge: 100%
          maxUnavailable: 100%
      admissionWebhooks:
        enabled: false
      service:
        enabled: false
      #   type: LoadBalancer
      #   externalTrafficPolicy: Local
      # Tried these as an alternative to externaltrafficpolicy, but
      # they wouldn't proxy correctly, everything was sent to the service that was running on the main domain
      hostPort:
        enabled: true
      # hostNetwork:
      #   enabled: true
      ingressClassResource:
        default: true
