---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      # version: 
  interval: 1m0s
  values:
    controller:
      admissionWebhooks:
        enabled: false
      service:
        enabled: false
        type: LoadBalancer
        externalTrafficPolicy: Cluster
      # Tried these as an alternative to externaltrafficpolicy, but
      # they wouldn't proxy correctly, everything was sent to the service that was running on the main domain
      # hostPort:
      #   enabled: true
      # hostNetwork:
      #   enabled: true
      ingressClassResource:
        default: true
