---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  chart:
    spec:
      chart: rook-ceph-cluster
      reconcileStrategy: ChartVersion
      version: "v1.16.2"
      sourceRef:
        kind: HelmRepository
        name: rook
  interval: 1m0s
  values:
    operatorNamespace: rook-ceph
    toolbox:
      enabled: true
    clusterName: ceph
    cephClusterSpec:
      Mgr:
        Count: 1
      Mon:
        Count: 1

