---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-operator
  namespace: ceph
spec:
  chart:
    spec:
      chart: rook-ceph
      reconcileStrategy: ChartVersion
      version: "v1.16.0"
      sourceRef:
        kind: HelmRepository
        name: rook
  interval: 1m0s
  # values:
  #   operatorNamespace: ceph
