apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: flux-system
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app.kubernetes.io/name: traefik
