apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: moonpiedumplings2@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    # solvers:
    #   - http01:
    #       ingress: {}

    # Use the DNS01 solver instead
    # only the DNS01 solver works for wildcard certs
    solvers:
      - selector:
          dnsZones:
            - moonpiedumpl.ing
        dns01:
          webhook:
            groupName: moonpiedumpl.ing
            solverName: porkbun
            config:
              apiKeySecretRef:
                name: porkbun-secret
                key: api-key
              secretKeySecretRef:
                name: porkbun-secret
                key: secret-key


            
