---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: libvirt
  namespace: openstack
spec:
  chart:
    spec:
      chart: libvirt
      version: "<=2025.2"
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openstack-helm
  interval: 1m0s
  install:
    disableWait: true
  valuesFrom:
    - kind: ConfigMap
      name: openstack-endpoints
      valuesKey: values.yaml
  values:
    manifests:
      role_cert_manager: true
    images:
      tags:
        libvirt: docker.io/openstackhelm/libvirt:2025.2-ubuntu_noble
    conf:
      ceph:
        enabled: true
      qemu:
        vnc_tls: "1"
        vnc_tls_x509_verify: "1"
