---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb
  namespace: openstack
spec:
  chart:
    spec:
      chart: mariadb
      version: "<=2025.2"
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openstack-helm
      # version: "2025.1.4"
  interval: 1m0s
  install:
    disableWait: true
  valuesFrom:
    - kind: ConfigMap
      name: openstack-endpoints
      valuesKey: values.yaml
    - kind: Secret
      name: openstack-secrets
      valuesKey: main-db
  values:
    images:
      tags:
        prometheus_mysql_exporter_helm_tests: quay.io/airshipit/heat:2025.1-ubuntu_noble
        ks_user: quay.io/airshipit/heat:2025.1-ubuntu_noble
    pod:
      replicas:
        server: 1