apiVersion: v1
kind: Secret
metadata:
    name: owui-secrets
    namespace: owui
type: Opaque
stringData:
    ssoClientSecret: ENC[AES256_GCM,data:XCw60hq48BBlfWtBWCFEXFQ8GsMZJzLcRAOqDrRlxHL2NCePi7H3nzl5KG83fdEt1p+F8lHRHV5WoDlDyjiJCZQARw6kC4XNTovYdVHcdamqg8cyPs4oElFBvAK16R+LVTEXRfxciMKlaVcSCC+K6AOWI2xEKvlCGFulY1F7Efw=,iv:p3KW6dAPplA4ZkLBwLxg668GhdZIUQL7iRsV6uuGEVQ=,tag:7/8IV36FwqmK5M0Z++5gZQ==,type:str]
    api-key: ENC[AES256_GCM,data:KWvcrWKN6yr7CsQ=,iv:kHrdtoxOC/uhMy2Xnjqm3mvp2robZOx9ZdVOkRdVVwM=,tag:mRMawvZrKzpQ/WVs9c5rhg==,type:str]
    basic-auth-ollama: ENC[AES256_GCM,data:9neOD7AMvACq+UFbPQ+ik0mZ0oX/,iv:xl3FGEdRYn1Ygn7YZqyKjY/nIg/1hmLJTnoeL8QRAP4=,tag:FkDL51S0NS71OdH23pYGeg==,type:str]
    ollama-auth-key: ENC[AES256_GCM,data:m+Pbj0eggsmslKjsdSE=,iv:CfY6BKEhwaRTqslgarUbZjIT71NT9RxFiDTzQuu9BQg=,tag:uMyp6jjsUThhVOZRTo5LNg==,type:str]
    #ENC[AES256_GCM,data:tZ6OZ8VwIhcgh3nG+If82PESHWtBXOL+kcs/ht3uPHbnRC1ZbBdH6WME0ADMWudiSWKKOaYcqqbxung59+ToZIcLRvEkXDvDlXGpJA==,iv:NqKimfZMeJzUFtVzF/gRLFbEDbE6NMHQ8KBndNI0Ufs=,tag:Lj3mtmzeWD9GYvTdQHv0Qw==,type:comment]
    PIPELINES_API_KEY: ENC[AES256_GCM,data:eeRQnCicCb5rdvhimjyqy1OJHbM=,iv:Mq4n0I2zRpPOV5mkT0+yCAeu4PpPo3nLGYESqI6pUyQ=,tag:lfgolf+XI6A7kNxO9GaBfQ==,type:str]
    OLLAMA_BASE_URL: ENC[AES256_GCM,data:1LA3PS/Hqu142neYNfgk+G2OYImJ7RuxFOGY+5x3MHDli6N49IXnhcxQ,iv:zvi7sukfRhuBeJHXn19kDZcwAf3V7OnUbAfSzFdLqr8=,tag:N3k00bZih1QLKSc8LifvXg==,type:str]
    #ENC[AES256_GCM,data:9jRUkYxJl9pBNZyP4p8UIIQI1LIwjTYsz9yFaRiBryL1ZMCytyGl71WhbYzxpNt0P3pzvZOOwa0wAOvl1MZJdSO4J6Fb2Qu2o+udHQloUz5U,iv:SZVPBTSAlcZUcFmEKebjQa/L0aNfLx3VT49z0jYfVMc=,tag:TSaUDXHZL7ku3rEH1ZNR3A==,type:comment]
    OPENAI_API_KEY: ENC[AES256_GCM,data:inPbLu9Tt03pHjDNYSx6SeZl22s=,iv:2mgicsxtfy86g1aTfZGIbCcBpWWMdevcFEDHGY0GPTc=,tag:qrN8wFUb8w4hOsAc4U5R7g==,type:str]
sops:
    age:
        - recipient: age1sg3u7ndj045gzv3u4w5t5kntplg6sz2hv6k3uxpxq85vtx56rc4s8q83gr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBranFQVVh1VjFmcGVCSlhF
            ajU1dGhhWUhOYnBHeENwV2FLZVhjTVlER2x3CjBoUVdzQWloc0pwVVZKbGd6aVVt
            dmoyZUtqM1hkdUl2NndOTVNjaWhkclUKLS0tIEtYd2xSSk9ndys2c2hWNSsxZDM1
            UmpEcHBOZWJEN1pwa0l5SkZjUHZ0em8K+INju3GAZpwZrAbp51TNJAnfQY9Hy61C
            cRllkble8byuq2wcAzlwoIqTZrWfVmSKbDTow3pFIetQaPjTQ5+RjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T06:09:54Z"
    mac: ENC[AES256_GCM,data:Fu8yjBF04XNRZlqAkLCVj10c2b0pOyfZB2c7qfraG9Jc2VajLLSrC3B5ViIly/1+mhLP41kc8jAKIEy35z4HS1eeNXsvIzeenP6IpxWs1W5lCChxiRwdQEdfOYofLtCD4cLwvxbaTNyWb/MbP6P/qAYKzHYZl4omZqmfp5N3t4w=,iv:5EUOHGs8ssYAM2U+mP4JV/VZ1IxoGlghEvboT5IKbDw=,tag:l9msVkTL5ZNeaAaBC5mduA==,type:str]
    encrypted_regex: ^(stringData)
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: owui-helm-secrets
    namespace: owui
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:UFRY+Ysj5v3oXZJ8SsP+Ly9ovYduNxbr/AOcKD3tSD/eM9eRxwIYxgcrYoSdgdbx1I7pWTC2UloePU57t6QNT9zZg4W9gMtn7Knj3/U/y3be5XRt,iv:fLjlLcB/8TZqBmmvOIvQuotlnKbL+jJTLWRKBADakb4=,tag:3hiB47T1Tqo07NoWLItlaw==,type:str]
sops:
    age:
        - recipient: age1sg3u7ndj045gzv3u4w5t5kntplg6sz2hv6k3uxpxq85vtx56rc4s8q83gr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBranFQVVh1VjFmcGVCSlhF
            ajU1dGhhWUhOYnBHeENwV2FLZVhjTVlER2x3CjBoUVdzQWloc0pwVVZKbGd6aVVt
            dmoyZUtqM1hkdUl2NndOTVNjaWhkclUKLS0tIEtYd2xSSk9ndys2c2hWNSsxZDM1
            UmpEcHBOZWJEN1pwa0l5SkZjUHZ0em8K+INju3GAZpwZrAbp51TNJAnfQY9Hy61C
            cRllkble8byuq2wcAzlwoIqTZrWfVmSKbDTow3pFIetQaPjTQ5+RjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T06:09:54Z"
    mac: ENC[AES256_GCM,data:Fu8yjBF04XNRZlqAkLCVj10c2b0pOyfZB2c7qfraG9Jc2VajLLSrC3B5ViIly/1+mhLP41kc8jAKIEy35z4HS1eeNXsvIzeenP6IpxWs1W5lCChxiRwdQEdfOYofLtCD4cLwvxbaTNyWb/MbP6P/qAYKzHYZl4omZqmfp5N3t4w=,iv:5EUOHGs8ssYAM2U+mP4JV/VZ1IxoGlghEvboT5IKbDw=,tag:l9msVkTL5ZNeaAaBC5mduA==,type:str]
    encrypted_regex: ^(stringData)
    version: 3.11.0
