---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: libvirt
  namespace: openstack
spec:
  chart:
    spec:
      chart: libvirt
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openstack-infra
  interval: 1m0s
  values:
    # It looks like conf.ceph.enabled: true is already the default
    images:
      tags:
        libvirt: docker.io/openstackhelm/libvirt:2024.1-ubuntu_jammy