---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb
  namespace: openstack
spec:
  chart:
    spec:
      chart: mariadb
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openstack-infra
  interval: 1m0s
  values:
    images:
      tags:
        prometheus_mysql_exporter_helm_tests: docker.io/openstackhelm/heat:2024.2-ubuntu_jammy
        ks_user: docker.io/openstackhelm/heat:2024.2-ubuntu_jammy
    pod:
      replicas:
        server: 1
