---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb
  namespace: openstack
spec:
  chart:
    spec:
      chart: mariadb
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openstack-helm
      # version: "2025.1.4"
  interval: 1m0s
  install:
    disableWait: true
  valuesFrom:
    - kind: ConfigMap
      name: openstack-endpoints
      valuesKey: values.yaml
  values:
    images:
      tags:
        prometheus_mysql_exporter_helm_tests: quay.io/airshipit/heat:2025.1-ubuntu_noble
        ks_user: quay.io/airshipit/heat:2025.1-ubuntu_noble
    pod:
      replicas:
        server: 1
    endpoints:
      oslo_db:
        auth:
          admin:
            username: root
            password: "${DB_ADMIN_PASS}"
          neutron:
            username: neutron
            password: securepassword
          keystone:
            username: keystone
            password: securepassword
          nova:
            username: nova
            password: securepassword
          glance:
            username: glance
            password: securepassword
          placement:
            username: placement
            password: securepassword
          nova_api:
            username: nova
            password: securepassword