---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: memcached
  namespace: openstack
spec:
  chart:
    spec:
      chart: memcached
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openstack-infra
  interval: 1m0s
  # values:
    # These appear to already be the default
    # pod:
    #   replicas:
    #     server: 1
