---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: openstack
spec:
  chart:
    spec:
      chart: rabbitmq
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openstack-infra
  interval: 1m0s
  values:
    images:
      tags:
        prometheus_rabbitmq_exporter_helm_tests: docker.io/openstackhelm/heat:2024.2-ubuntu_jammy
        rabbitmq_init: docker.io/openstackhelm/heat:2024.2-ubuntu_jammy
    pod:
      replicas:
        server: 1
