---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  chart:
    spec:
      chart: openebs
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openebs
      version: "4.3.2"
  interval: 1m0s
  values:
    engines:
      local:
        lvm:
          enabled: false
        rawfile:
          enabled: true
        zfs:
          enabled: false
      replicated:
        mayastor:
          enabled: false
    loki:
      enabled: false
      minio:
        enabled: false
    alloy:
      enabled: false