---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cinder
  namespace: openstack
spec:
  chart:
    spec:
      chart: cinder
      version: "<=2025.2"
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openstack-helm
  interval: 1m0s
  timeout: 30m0s
  install:
    disableWait: true
  dependsOn:
    - name: mariadb
    - name: memcached
    - name: rabbitmq
    - name: keystone
  valuesFrom:
    - kind: ConfigMap
      name: openstack-endpoints
      valuesKey: values.yaml
    - kind: Secret
      name: openstack-secrets
      valuesKey: oslo-db
    - kind: Secret
      name: openstack-secrets
      valuesKey: oslo-messaging
    - kind: Secret
      name: openstack-secrets
      valuesKey: oslo-cache
    - kind: Secret
      name: openstack-secrets
      valuesKey: cinder-identity
  values:
    images:
      tags:
        db_init: "quay.io/airshipit/heat:2025.2-ubuntu_noble"
        cinder_db_sync: "quay.io/airshipit/cinder:2025.2-ubuntu_noble"
        db_drop: "quay.io/airshipit/heat:2025.2-ubuntu_noble"
        ks_user: "quay.io/airshipit/heat:2025.2-ubuntu_noble"
        ks_service: "quay.io/airshipit/heat:2025.2-ubuntu_noble"
        ks_endpoints: "quay.io/airshipit/heat:2025.2-ubuntu_noble"
        cinder_api: "quay.io/airshipit/cinder:2025.2-ubuntu_noble"
        bootstrap: "quay.io/airshipit/heat:2025.2-ubuntu_noble"
        cinder_scheduler: "quay.io/airshipit/cinder:2025.2-ubuntu_noble"
        cinder_volume: "quay.io/airshipit/cinder:2025.2-ubuntu_noble"
        cinder_volume_usage_audit: "quay.io/airshipit/cinder:2025.2-ubuntu_noble"
        cinder_db_purge: "quay.io/airshipit/cinder:2025.2-ubuntu_noble"
        cinder_storage_init: "docker.io/openstackhelm/ceph-config-helper:latest-ubuntu_jammy"
        cinder_backup: "quay.io/airshipit/cinder:2025.2-ubuntu_noble"
        cinder_backup_storage_init: "docker.io/openstackhelm/ceph-config-helper:latest-ubuntu_jammy"