---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: glance
  namespace: openstack
spec:
  chart:
    spec:
      chart: glance
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openstack-helm
  interval: 1m0s
  install:
    disableWait: true
  dependsOn:
    - name: mariadb
    - name: memcached
    - name: rabbitmq
    - name: keystone
  valuesFrom:
    - kind: ConfigMap
      name: openstack-endpoints
      valuesKey: values.yaml
    - kind: Secret
      name: openstack-secrets
      valuesKey: oslo-db
    - kind: Secret
      name: openstack-secrets
      valuesKey: oslo-messaging
    - kind: Secret
      name: openstack-secrets
      valuesKey: oslo-cache
    - kind: Secret
      name: openstack-secrets
      valuesKey: glance-identity
  values:
    images:
      tags:
        bootstrap: "quay.io/airshipit/heat:2025.1-ubuntu_noble"
        db_init: "quay.io/airshipit/heat:2025.1-ubuntu_noble"
        db_drop: "quay.io/airshipit/heat:2025.1-ubuntu_noble"
        ks_user: "quay.io/airshipit/heat:2025.1-ubuntu_noble"
        ks_service: "quay.io/airshipit/heat:2025.1-ubuntu_noble"
        ks_endpoints: "quay.io/airshipit/heat:2025.1-ubuntu_noble"
        glance_db_sync: "quay.io/airshipit/glance:2025.1-ubuntu_noble"
        glance_api: "quay.io/airshipit/glance:2025.1-ubuntu_noble"
        glance_metadefs_load: "quay.io/airshipit/glance:2025.1-ubuntu_noble"
        glance_storage_init: "docker.io/openstackhelm/ceph-config-helper:latest-ubuntu_jammy"
    # As opposed to rbd, pvc
    storage: pvc
    volume:
      class_name: general
      size: 500Gi
    conf:
      glance:
        # DEFAULT:
        #   workers: 2
      glance_api_uwsgi:
        uwsgi:
          chunked-input-limit: "4096000"
          http-auto-chunked: true
          http-raw-body: true
          socket-timeout: 10
    network:
      api:
        ingress:
          public: true
          classes:
            namespace: "nginx"
            cluster: "nginx-cluster"
          annotations:
            nginx.ingress.kubernetes.io/rewrite-target: /
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
            cert-manager.io/cluster-issuer: letsencrypt-prod