---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: glance
  namespace: openstack
spec:
  chart:
    spec:
      chart: glance
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openstack-helm
  interval: 1m0s
  install:
    disableWait: true
  dependsOn:
    - name: mariadb
    - name: memcached
    - name: rabbitmq
    - name: keystone
  valuesFrom:
    - kind: ConfigMap
      name: openstack-endpoints
      valuesKey: values.yaml
    - kind: Secret
      name: openstack-secrets
      valuesKey: oslo-db
    - kind: Secret
      name: openstack-secrets
      valuesKey: oslo-messaging
    - kind: Secret
      name: openstack-secrets
      valuesKey: oslo-cache
    - kind: Secret
      name: openstack-secrets
      valuesKey: glance-identity
  values:
    images:
      tags:
        bootstrap: "quay.io/airshipit/heat:2025.1-ubuntu_noble"
        db_init: "quay.io/airshipit/heat:2025.1-ubuntu_noble"
        db_drop: "quay.io/airshipit/heat:2025.1-ubuntu_noble"
        ks_user: "quay.io/airshipit/heat:2025.1-ubuntu_noble"
        ks_service: "quay.io/airshipit/heat:2025.1-ubuntu_noble"
        ks_endpoints: "quay.io/airshipit/heat:2025.1-ubuntu_noble"
        glance_db_sync: "quay.io/airshipit/glance:2025.1-ubuntu_noble"
        glance_api: "quay.io/airshipit/glance:2025.1-ubuntu_noble"
        glance_metadefs_load: "quay.io/airshipit/glance:2025.1-ubuntu_noble"
        glance_storage_init: "docker.io/openstackhelm/ceph-config-helper:latest-ubuntu_jammy"
    storage: pvc
    volume:
      class_name: general
      size: 2Gi