---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keystone
  namespace: openstack
spec:
  chart:
    spec:
      chart: keystone
      version: "<=2025.2"
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openstack-helm
  interval: 1m0s
  timeout: 30m0s
  install:
    disableWait: true
  dependsOn:
    - name: mariadb
    - name: memcached
    - name: rabbitmq
  valuesFrom:
    - kind: ConfigMap
      name: openstack-endpoints
      valuesKey: values.yaml
    - kind: Secret
      name: openstack-secrets
      valuesKey: oslo-db
    - kind: Secret
      name: openstack-secrets
      valuesKey: oslo-messaging
    - kind: Secret
      name: openstack-secrets
      valuesKey: oslo-cache
    - kind: Secret
      name: openstack-secrets
      valuesKey: keystone-identity
  values:
    images:
      tags:
        bootstrap: "quay.io/airshipit/heat:2025.2-ubuntu_noble"
        db_init: "quay.io/airshipit/heat:2025.2-ubuntu_noble"
        db_drop: "quay.io/airshipit/heat:2025.2-ubuntu_noble"
        # keystone_api: "quay.io/airshipit/keystone:2025.2-ubuntu_noble"
        # Custom image comes with apache mod openid
        keystone_api: "docker.io/moonpiedumplings/keystone:2025.2-ubuntu_noble"
        keystone_bootstrap: "quay.io/airshipit/heat:2025.2-ubuntu_noble"
        keystone_credential_rotate: "quay.io/airshipit/keystone:2025.2-ubuntu_noble"
        keystone_credential_setup: "quay.io/airshipit/keystone:2025.2-ubuntu_noble"
        keystone_db_sync: "quay.io/airshipit/keystone:2025.2-ubuntu_noble"
        keystone_domain_manage: "quay.io/airshipit/keystone:2025.2-ubuntu_noble"
        keystone_fernet_rotate: "quay.io/airshipit/keystone:2025.2-ubuntu_noble"
        keystone_fernet_setup: "quay.io/airshipit/keystone:2025.2-ubuntu_noble"
        ks_user: "quay.io/airshipit/heat:2025.2-ubuntu_noble"
    pod:
      mounts:
        keystone_api:
          keystone_api:
            volumeMounts:
              - name: oidc-secrets
                mountPath: /etc/oidc-secret
                readOnly: true
            volumes:
              - name: oidc-secrets
                secret:
                  secretName: openstack-oidc-secrets
    network:
      api:
        ingress:
          public: true
          classes:
            namespace: "nginx"
            cluster: "nginx-cluster"
          annotations:
            nginx.ingress.kubernetes.io/rewrite-target: /
            cert-manager.io/cluster-issuer: letsencrypt-prod
    conf:
      keystone:
        auth:
          methods: password,token,openid,mapped,application_credential
        openid:
          remote_id_attribute: HTTP_OIDC_ISS
        federation:
          trusted_dashboard:
            type: multistring
            values:
              - https://openstack.moonpiedumpl.ing/auth/websso/
          default_authorization_ttl: 720
        cache:
          backend_argument: memcached_expire_time:3600
        DEFAULT:
          max_token_size: 512
      # See https://docs.openstack.org/releasenotes/keystone/2025.1.html
      # See https://opendev.org/openstack/keystone/commit/0d2cc1a3af4dbd2825cef5992056bffe935eaadd
      # Must be set twice I think, once in conf and once top level
      wsgi_script_name: "wsgi.py"
      wsgi_keystone: |
        {{- $portInt := tuple "identity" "service" "api" $ | include "helm-toolkit.endpoints.endpoint_port_lookup" }}
        {{- $wsgiScript := .Values.conf.wsgi_script_name }}

        Listen 0.0.0.0:{{ $portInt }}

        LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
        LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" proxy

        SetEnvIf X-Forwarded-For "^.*\..*\..*\..*" forwarded
        CustomLog /dev/stdout combined env=!forwarded
        CustomLog /dev/stdout proxy env=forwarded
        ErrorLog /dev/stderr

        <VirtualHost *:{{ $portInt }}>
            WSGIDaemonProcess keystone-public processes=1 threads=1 user=keystone group=keystone display-name=%{GROUP}
            WSGIProcessGroup keystone-public
            WSGIScriptAlias / /var/www/cgi-bin/keystone/{{ $wsgiScript }}
            WSGIApplicationGroup %{GLOBAL}
            WSGIPassAuthorization On
            ErrorLogFormat "%{cu}t %M"
            ErrorLog /dev/stdout


            # OIDC
            OIDCClaimPrefix "OIDC-"
            OIDCRemoteUserClaim preferred_username
            OIDCSessionType server-cache
            OIDCXForwardedHeaders X-Forwarded-Host X-Forwarded-Proto X-Forwarded-Port
            OIDCResponseType "code"
            OIDCScope "openid email profile groups"
            OIDCProviderMetadataURL "https://idp.moonpiedumpl.ing/application/o/openstack/"

            OIDCClientID 5oIuKo60MxCdwiE1yQ33oGRMmKx3ZlMUIK9bAmhQ
            OIDCClientSecret "exec:/bin/cat /etc/oidc-secret/client-secret"
            OIDCCryptoPassphrase "exec:/bin/bash -c \"head /dev/urandom | tr -dc A-Za-z0-9 | head -c 32\""
            OIDCCacheType shm
            OIDCClaimDelimiter ;

            # avoid redirect issues per the following
            # https://review.opendev.org/c/openstack/keystone/+/925553
            OIDCRedirectURI https://{{- tuple "identity" "public" $ | include "helm-toolkit.endpoints.hostname_fqdn_endpoint_lookup" -}}/redirect_uri
            <Location ~ "/redirect_uri">
              Require valid-user
              AuthType openid-connect
            </Location>

            # add using the identity provider 'sso' with the protocol 'openid'
            <Location /v3/OS-FEDERATION/identity_providers/sso/protocols/openid/auth>
              Require valid-user
              AuthType openid-connect
            </Location>
            # websso support
            <Location /v3/auth/OS-FEDERATION/websso/openid>
              Require valid-user
              AuthType openid-connect
            </Location>
            <Location /v3/auth/OS-FEDERATION/identity_providers/sso/protocols/openid/websso>
              Require valid-user
              AuthType openid-connect
            </Location>
        </VirtualHost>


