---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: neutron
  namespace: openstack
spec:
  chart:
    spec:
      chart: neutron
      version: "<=2025.2"
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openstack-helm
  interval: 1m0s
  timeout: 30m0s
  install:
    disableWait: true
  dependsOn:
    - name: mariadb
    - name: memcached
    - name: rabbitmq
    - name: keystone
  valuesFrom:
    - kind: ConfigMap
      name: openstack-endpoints
      valuesKey: values.yaml
    - kind: Secret
      name: openstack-secrets
      valuesKey: oslo-db
    - kind: Secret
      name: openstack-secrets
      valuesKey: oslo-messaging
    - kind: Secret
      name: openstack-secrets
      valuesKey: oslo-cache
    - kind: Secret
      name: openstack-secrets
      valuesKey: neutron-identity
  values:
    images:
      tags:
        bootstrap: "quay.io/airshipit/heat:2025.2-ubuntu_noble"
        db_init: "quay.io/airshipit/heat:2025.2-ubuntu_noble"
        db_drop: "quay.io/airshipit/heat:2025.2-ubuntu_noble"
        ks_user: "quay.io/airshipit/heat:2025.2-ubuntu_noble"
        ks_service: "quay.io/airshipit/heat:2025.2-ubuntu_noble"
        ks_endpoints: "quay.io/airshipit/heat:2025.2-ubuntu_noble"
        neutron_db_sync: "quay.io/airshipit/neutron:2025.2-ubuntu_noble"
        # neutron_dhcp: "quay.io/airshipit/neutron:2025.2-ubuntu_noble"
        # FIXME: This image is built with the critical bug fix
        # https://review.opendev.org/c/openstack/neutron/+/962871
        # Use vanilla image when the fix is merged and backported to 2025.2
        neutron_dhcp: "quay.io/kozhukalov/neutron:2025.2-ubuntu_noble_custom"
        neutron_l3: "quay.io/airshipit/neutron:2025.2-ubuntu_noble"
        neutron_l2gw: "quay.io/airshipit/neutron:2025.2-ubuntu_noble"
        neutron_linuxbridge_agent: "quay.io/airshipit/neutron:2025.2-ubuntu_noble"
        neutron_metadata: "quay.io/airshipit/neutron:2025.2-ubuntu_noble"
        neutron_ovn_metadata: "quay.io/airshipit/neutron:2025.2-ubuntu_noble"
        neutron_openvswitch_agent: "quay.io/airshipit/neutron:2025.2-ubuntu_noble"
        neutron_server: "quay.io/airshipit/neutron:2025.2-ubuntu_noble"
        neutron_rpc_server: "quay.io/airshipit/neutron:2025.2-ubuntu_noble"
        neutron_bagpipe_bgp: "quay.io/airshipit/neutron:2025.2-ubuntu_noble"
        neutron_netns_cleanup_cron: "quay.io/airshipit/neutron:2025.2-ubuntu_noble"
    conf:
      neutron:
        DEFAULT:
          l3_ha: False
          max_l3_agents_per_router: 1
      # <provider_interface_name> will be attached to the br-ex bridge.
      # The IP assigned to the interface will be moved to the bridge.
      auto_bridge_add:
        br-ex: eth2
      plugins:
        ml2_conf:
          ml2_type_flat:
            flat_networks: public,incus
        openvswitch_agent:
          ovs:  
            bridge_mappings: public:br-ex,incus:br-inc
    network:
      server:
        ingress:
          public: true
          classes:
            namespace: "nginx"
            cluster: "nginx-cluster"
          annotations:
            nginx.ingress.kubernetes.io/rewrite-target: /
            cert-manager.io/cluster-issuer: letsencrypt-prod