apiVersion: v1
kind: Secret
metadata:
    name: owui-secrets
    namespace: owui
type: Opaque
stringData:
    ssoClientSecret: ENC[AES256_GCM,data:XCw60hq48BBlfWtBWCFEXFQ8GsMZJzLcRAOqDrRlxHL2NCePi7H3nzl5KG83fdEt1p+F8lHRHV5WoDlDyjiJCZQARw6kC4XNTovYdVHcdamqg8cyPs4oElFBvAK16R+LVTEXRfxciMKlaVcSCC+K6AOWI2xEKvlCGFulY1F7Efw=,iv:p3KW6dAPplA4ZkLBwLxg668GhdZIUQL7iRsV6uuGEVQ=,tag:7/8IV36FwqmK5M0Z++5gZQ==,type:str]
    api-key: ENC[AES256_GCM,data:KWvcrWKN6yr7CsQ=,iv:kHrdtoxOC/uhMy2Xnjqm3mvp2robZOx9ZdVOkRdVVwM=,tag:mRMawvZrKzpQ/WVs9c5rhg==,type:str]
sops:
    age:
        - recipient: age1sg3u7ndj045gzv3u4w5t5kntplg6sz2hv6k3uxpxq85vtx56rc4s8q83gr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBranFQVVh1VjFmcGVCSlhF
            ajU1dGhhWUhOYnBHeENwV2FLZVhjTVlER2x3CjBoUVdzQWloc0pwVVZKbGd6aVVt
            dmoyZUtqM1hkdUl2NndOTVNjaWhkclUKLS0tIEtYd2xSSk9ndys2c2hWNSsxZDM1
            UmpEcHBOZWJEN1pwa0l5SkZjUHZ0em8K+INju3GAZpwZrAbp51TNJAnfQY9Hy61C
            cRllkble8byuq2wcAzlwoIqTZrWfVmSKbDTow3pFIetQaPjTQ5+RjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-03T20:42:57Z"
    mac: ENC[AES256_GCM,data:AryNHOuFl1CoApTnvCmoW5yuTmJok8z1jDdNvHIikvaWUGhyCwAM6s0aFsGpfyWcKxJib6oBjCqXXTWCDMSeK7mJoEu7grejpUu3UOTU5PofyQKAECKf868uURxBpzq7dug34kkFMJ75be/EMsoKCIwk8CqSTajfXcZOQjS8VTM=,iv:k2sWhb+9JRnVwPFBdLHEFvqHc95ECJaV1sMk+V9mX7A=,tag:SoquTeocJV5xQaP0x33jHQ==,type:str]
    encrypted_regex: ^(stringData)
    version: 3.10.2
