---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama
  namespace: owui
spec:
  resources:
    requests:
      storage: 60Gi
  volumeMode: Filesystem
  storageClassName: general
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openwebui
  namespace: owui
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  storageClassName: general
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: owui-pipelines
  namespace: owui
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  storageClassName: general
  accessModes:
    - ReadWriteOnce
