---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 1m0s
  path: ./kustomize
  prune: false
  sourceRef:
    kind: GitRepository
    name: podinfo
  targetNamespace: default
