apiVersion: v1
kind: Secret
metadata:
    name: coder-secrets
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:UaOOHDssUx7sc2M0/WKpiNCmgniFkE+EUR+pZeWM5EUXMFl2EG/XeLQkQgVucoGdb59MBWIHaTroxQGjDWZr73Eg0fyOgJbdBSNqEnEbY3QA5w5Q8elW8m5/3TPHWRM7eJUM5ifiIrSWMVGbU5u1lR/1DiyYJ6N+OiExGl11dBVK6V7lRLINsYmpxrelPM9dAE4FZcv4HolAiBHAWfIHG5jPapoR7hrNBQUqR/q+1UfFgib5jLs4ZKcvumtmtbiKbOT5IaveN8BMq0hWQ6+DgffYSgV4NfQMuxJ35vHzZ1JeabKVuCzJpdqO5pheah7VAdUg7TrqQqrEcvqd0b09/QV9U2D4Pfoqt9safh6lXNKF9sNW5bBW/rZUawBSYcTb9OypE5F9Wm2cs7sPdB6AdEJAbmFlmShf0RmF6YC92fN6dfCo6XHH5PtQss30G/2W///QysQeFIzlMJ/Lp8UN1feOZg==,iv:kpqdYs/cJ4n9W53T3thDpdNEmIYYtLrENfnVStB8V8M=,tag:UyJZ+R53kpjqdaSeYaYNkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sg3u7ndj045gzv3u4w5t5kntplg6sz2hv6k3uxpxq85vtx56rc4s8q83gr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNEx0eVh2VVhUZjVkRkM3
            TS9wYy9rMEQ0NGlaTGh1T1FaQ2pFZUw3OUFJCmNDZjVaNFMyZXcwRngwQkVZbTIv
            SUNYcGxDaUg5eWlWMUhPbWdVVnlSSlUKLS0tIDZyKzIrdlZLS3M0eVFmVDZQUGJW
            NFdTT3VQWHlIdjlIVGVGM2FNWUdQSUEKDyDWsmqoYwkgGe5Aiur/UZrDNI+1LzXT
            SiOExoj/O8LakECHnuJlJBYXJpJ5n6C5DOqzEiidxKJHwTI5jdQ0vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-05T22:38:22Z"
    mac: ENC[AES256_GCM,data:eSyvU3XSVBWjHh+n7/2FZeiDB1CZrFSHxI5/rlYO/NvvOZfbrDezmdkBLifb7P3V+muNS5keeYl75+pSApTSyzLUT4RzT+lc178DFFaVwoovZphPp5VgkM51TW7eKuF8P2mQjS/btslBe96/KFLaJChDTU3rThBOCo6Mg/cfKrg=,iv:mF0jD8hIHV37hikCJ8wxqu1UtGFTYEfMhKl9LMIBvjA=,tag:z7UnaZInkcoJHJ7/TovzBw==,type:str]
    pgp: []
    encrypted_regex: ^(values.yaml)$
    version: 3.9.4
