---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-postgres
  namespace: authentik
spec:
  instances: 1
  # See rolling updates
  # https://cloudnative-pg.io/documentation/1.27/postgres_upgrades/
  imageName: ghcr.io/cloudnative-pg/postgresql:17.6
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi
      storageClassName: longhorn-databases
      volumeMode: Filesystem
  backup:
    volumeSnapshot:
       className: longhorn-snapshot
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-db-secret
  managed:
    services:
      disabledDefaultServices: ["ro", "r"] 
---
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: daily-authentik
  namespace: authentik
  annotations:
    backup.cnpg.io/volumeSnapshotDeadline: "20"
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: authentik-postgres
  method: volumeSnapshot
  immediate: true


