---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  chart:
    spec:
      chart: authentik
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: authentik
        # Figure out what version I should have
      version: "<=2025.8"
  interval: 1m0s
  valuesFrom:
    - kind: Secret
      name: authentik-secrets
      valuesKey: values.yaml
  values:
    authentik:
        # secret_key: "PleaseGenerateASecureKey"
        # This sends anonymous usage-data, stack traces on errors and
        # performance data to sentry.io, and is fully opt-in
        error_reporting:
            enabled: true
        postgresql:
          enabled: false
          host: authentik-postgres-rw.authentik.svc.cluster.local
          # password: "ThisIsNotASecurePassword"
        redis:
          enabled: true
          host: "authentik-redis-master.authentik.svc.cluster.local"
    server:
      ingress:
          # Should default to nginx already
          # ingressClassName: nginx
          # Change to true when done
          enabled: true
          hosts:
              - idp.moonpiedumpl.ing
          annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
              acme.cert-manager.io/http01-edit-in-place: "true"
          tls:
            - hosts: [idp.moonpiedumpl.ing]
              secretName: sso-acme
    postgresql:
      enabled: false
    redis:
      enabled: true
      auth:
        enabled: true
  